### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by Frerol** [ychoi-kr/omegat-plugin-openai-translate#1]
The plugin doesn't appear to be working. I did exactly as stated in the readme file.

**Comment by ychoi-kr** [comment]
Sorry to hear that. Do you have any error message?

**Comment by TransLingua** [comment]
When you say: "- macOS: Copy the plug-in file into /Applications/OmegaT.app/Contents/Java/plugins directory."
Did you mean Folder or file? 
If it is "file" that you meant instead of a folder, which file, please
There is no jar file!
Many thanks

**Comment by Frerol** [comment]
Well, no error message shows up. My OmegaT is set up to automatically request the translation. Google's appears normally, yours doesn't. How can I check for error messages?

**Comment by ychoi-kr** [comment]
@TransLingua 
You can find the jar file in [releases](https://github.com/ychoi-kr/omegat-plugin-openai-translate/releases).
