### ISSUE TITLE
Feature Request: Add server configuration for local LLM

### ISSUE THREAD

**Issue by nogajun** [ychoi-kr/omegat-plugin-openai-translate#6]
In order to use the OpenAI compatible API for local LLM, I would like to be able to use API URLs other than OpenAI.

**Comment by ychoi-kr** [comment]
I think it would be better to create a separate plug-in for this. OmegaT lets you use multiple machine translation engines at the same time, so having a different plug-in for the local LLM would make it easier to compare and pick between OpenAI’s models and the local one. Plus, different LLMs might work better with their own specific prompts, so keeping them separate could help optimize the results.

If you're up for it, I’d recommend forking this project and building a new plug-in that specifically supports local LLMs. This way, users get more options and flexibility. While tweaking the existing plug-in could work, I think managing them separately might be more efficient in the long run.
